# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random, no regular
# words or you'll be exposed to dictionary attacks. You can use `rake secret` to
# generate a secure secret key.

# Make sure the secrets in this file are kept private if you're sharing your
# code publicly.

# MY NOTE: These are included in all other sections below. You can override any
# variable here by redefining it in the desired section.
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # Facebook app info (for authentication using Onmiauth)
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  # Google OAuth2 info (for authentication using Omniauth)
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  # Access token for native apps
  app_access_token: <%= ENV["APP_ACCESS_TOKEN"] %>
  # AWS info (for AWS integration, for example for the media library)
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>
  aws_cf_key_pair_id: <%= ENV["AWS_CF_KEY_PAIR_ID"] %>
  aws_cf_private_key: <%= ENV["AWS_CF_PRIVATE_KEY"] %>
  aws_cf_distribution: <%= ENV["AWS_CF_DISTRIBUTION"] %>
  # JW Player account token (for playing back video attachments)
  jw_player_account_token: <%= ENV["JW_PLAYER_ACCOUNT_TOKEN"] %>
  # Email delivery info
  application_host: <%= ENV["APPLICATION_HOST"] %>
  outgoing_email_sender: <%= ENV["OUTGOING_EMAIL_SENDER"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_authentication: <%= ENV["SMTP_AUTHENTICATION"] %>
  smtp_enable_starttls_auto: <%= ENV["SMTP_ENABLE_STARTTLS_AUTO"] %>
  smtp_openssl_verify_mode: <%= ENV["SMTP_OPENSSL_VERIFY_MODE"] %>

development:
  <<: *defaults
  secret_key_base: 20386981364ffde79760c1fbb2a7a0a6825666911881bbc0aeeda5a5863b1e9582839fc12972ce88cb169f1eeb04e4e89d0a3514d450a3ca97fc11c67da1416d
  # Email delivery info
  application_host: localhost:5000

test:
  <<: *defaults
  secret_key_base: 30c6bf96ac41b012f3eb9ead75d5dc779bc54febabb2d18897b0e6d5225ee3f5452f106cab2e954a1966789e3d69eda4058daf8db87db1b6ff8ef8cd66e2fca1
  # AWS info (dummy values needed to allow tests to run)
  aws_secret_access_key: dummy-secret-access-key

# Do not keep production secrets in the repository, instead read values from the
# environment.
production:
  <<: *defaults
  # CDN for serving Dragonfly processed images
  dragonfly_cdn: <%= ENV["DRAGONFLY_CDN"] %>
